# to Add Colors ro man page
export LESS_TERMCAP_mb=$'\E[1;31m'       # Start blinking (red)
export LESS_TERMCAP_md=$'\E[1;36m'       # Start bold (cyan)
export LESS_TERMCAP_me=$'\E[0m'          # End mode
export LESS_TERMCAP_so=$'\E[01;44;37m'  # Start standout (white on blue)
export LESS_TERMCAP_se=$'\E[0m'          # End standout
export LESS_TERMCAP_us=$'\E[1;32m'       # Start underline (green)
export LESS_TERMCAP_ue=$'\E[0m'          # End underline
